DROP TABLE G4_CONFERENCIAS.NaoEstudante;

DROP TABLE G4_CONFERENCIAS.Estudante;

DROP TABLE G4_CONFERENCIAS.Escreve;

DROP TABLE G4_CONFERENCIAS.Autor;

DROP TABLE G4_CONFERENCIAS.Artigo;

DROP TABLE G4_CONFERENCIAS.Pessoa;

DROP TABLE G4_CONFERENCIAS.Instituicao;

DROP SCHEMA G4_CONFERENCIAS;
GO
