apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-jpcg-pvc
  namespace: jpcg 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
