

DROP TABLE G4_GESTAO_STOCKS.CondicoesPagamento;

DROP TABLE G4_GESTAO_STOCKS.TaxaIva;

DROP TABLE G4_GESTAO_STOCKS.Contem;

DROP TABLE G4_GESTAO_STOCKS.Encomenda;

DROP TABLE G4_GESTAO_STOCKS.Fornecedor;

DROP TABLE G4_GESTAO_STOCKS.TipoFornecedor;

DROP TABLE G4_GESTAO_STOCKS.Produto;

DROP TABLE G4_GESTAO_STOCKS.Armazem;

DROP SCHEMA G4_GESTAO_STOCKS;
GO