version: "3.8"
services:
    app:
        image: cherrypy_app
        build:
            context: .
            dockerfile: Dockerfile.app
        volumes:
            - www:/app/www
        deploy:
            replicas: 5
    nginx:
        image: nginx
        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf       
        ports:
            - 80:80
            - 443:443
        secrets:
           - source: cert
             target: /etc/ssl/private/cert.pem
           - source: key
             target: /etc/ssl/private/key.pem
secrets:
    cert:
        file: cert.pem
    key:
        file: key.pem

volumes:
    www:

configs:
    nginx_conf:
        file: nginx.conf


