
DROP TABLE G4_RENT_CAR.Pesado;

DROP TABLE G4_RENT_CAR.Ligeiro;

DROP TABLE G4_RENT_CAR.Similaridade;

DROP TABLE G4_RENT_CAR.Aluguer;

DROP TABLE G4_RENT_CAR.Veiculo;

DROP TABLE G4_RENT_CAR.TipoVeiculo;

DROP TABLE G4_RENT_CAR.Balcao;

DROP TABLE G4_RENT_CAR.Cliente;

DROP SCHEMA G4_RENT_CAR;
GO